### ISSUE TITLE
Deprecate snake_case symbols (warning level forever) in favor of names following Kotlin conventions

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/lets-plot-kotlin#44]
For reference, I'm linking the official naming conventions of Kotlin: https://kotlinlang.org/docs/coding-conventions.html#naming-rules

I'm suggesting to always keep the snake_case symbols at warning deprecation level for discoverability when people come from Python, quite like the deprecated symbols in kotlinx.coroutines for people coming from RxJava or RxWhatever, except that here, it'd compile and run, so you can see it work before making it idiomatic.

**Comment by alshan** [comment]
The Let's-plot Kotlin API was designed this way (copied from ggplot2 API, frankly) keeping in mind the people who use and love the original ggplot2 library in R or its Python ports (there are some, including Lets-plot itself).

Note that Let's-plot API is not following neither Kotlin nor Python's PEP 8 style guides as it's classes and functions alike use snake_case symbols.

We are not planning to deprecate these symbols in Lets-plot (if this is your proposal) but, I heard there is another plotting API in developement, which would be 100% Kotlin idiomatic so that one can choose according to preferences.

**Comment by holgerbrandl** [comment]
Although being a long term (10y+) R professional ,  it feels not _kotlinesque_ (but imho rather inconvenient) to deviate from java/kotlin naming conventions here.

One beauty of kotlin for data-science is, that it ties in naturally into complex domain models written in kotlin/java, so providing a natural API experience clearly outweighs the initial mental migration when coming from r to kotlin.

A third strong argument imho in favor of kotlin naming conventions for lets-plot-jvm is, that the intersection of R users and kotlin developers is rather small. Even after years of searching for such like-minded colleagues, I have not personally met a single one yet (except myself in the mirror). Cleary there is a lot of perception bias in this argument, however I still think its valid more generally. 

A kotlin-naming-compliant ggplot API can look very natural, see https://github.com/holgerbrandl/kravis#first-example. Clearly, I'd prefer lets-plot here in the long run, because of its much better backend implementation (that does not rely on R/ggplot itself).

**Comment by alshan** [comment]
An expression like:

`lets_plot() + geom_point() + ggsize()`

if brought in compliance with kotlin naming convention, would look: 

`letsPlot() + GeomPoint() + ggsize()`

All right, it less resembles ggplot2 and ugly on its face. I just don't see a value in such transition.
